copyright: 2020 David Canagasabey
maintainer: david@dtcan.dec
dependencies:
- mtl
- base >= 4.7 && < 5
name: arithmetic
version: 0.1.0.0
extra-source-files:
- README.md
author: David Canagasabey
github: dtcan/arithmetic
license: MIT
executables:
  arithmetic-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
description: Please see the README on GitHub at <https://github.com/dtcan/arithmetic#readme>
